version: "3.8"

services:
  nextjs:
    container_name: frontend-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
